name: tzuchi-teaching
region: nyc

# 靜態前端網站
static_sites:
  - name: frontend
    github:
      repo: tzustu63/tzuchi-teaching
      branch: V1
      deploy_on_push: true
    source_dir: /frontend
    output_dir: /
    index_document: index.html
    error_document: index.html
    routes:
      - path: /
    cors:
      allow_origins:
        - exact: "*"
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS

# 後端 Web 服務
services:
  - name: backend
    github:
      repo: tzustu63/tzuchi-teaching
      branch: V1
      deploy_on_push: true
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CLAUDE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: GAMMA_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ENVIRONMENT
        value: production
        scope: RUN_TIME
      - key: DEBUG
        value: "false"
        scope: RUN_TIME
      - key: PORT
        value: "8000"
        scope: RUN_TIME
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
# 資料庫（可選，如果需要 PostgreSQL）
# 取消註解以啟用
# databases:
#   - name: postgres
#     engine: PG
#     version: "15"
#     production: false  # 設為 true 使用生產資料庫（更昂貴）

# 域名配置（可選）
# domains:
#   - domain: your-domain.com
#     type: PRIMARY
#     zone: your-domain.com
